### PR TITLE
Update to v1.1.0

### PR DESCRIPTION
**Pull request by halldc**

### CODE REVIEW

**Comment by halldc** [comment]
@conda-forge-admin, please rerender

**Comment by halldc** [comment]
Failing because `r-httpuv >=1.4.3` is unavailable from conda-forge.

**Comment by halldc** [comment]
@bgruening I think we need both the changes in #2 (i.e. which R versions to build), but we also need the changes in my PR (i.e. the specific dependency versions).

**Comment by halldc** [comment]
@conda-forge-admin, please rerender

**Comment by halldc** [comment]
Depends on https://github.com/conda-forge/r-sourcetools-feedstock/pull/3

**Comment by halldc** [comment]
Depends on adding R 3.5.1 builds to these:
- https://github.com/conda-forge/r-httpuv-feedstock/pull/9
- https://github.com/conda-forge/r-htmltools-feedstock/pull/2
- https://github.com/conda-forge/r-xtable-feedstock/pull/1

**Comment by halldc** [comment]
@bgruening This is now good to merge 🎊

**Comment by bgruening** [comment]
:tada:

**Pull request merged**
